- bg: main-slider-1-1.jpg
  tagline: ideal place to unwind
  heading: Beauty Salon
  cta-url: /contact
  cta-title: Book Now
- bg: main-slider-1-2.jpg
  tagline: ideal place to unwind
  heading: Spa Center
  cta-url: /contact
  cta-title: Book Now
- bg: main-slider-1-3.jpg
  tagline: ideal place to unwind
  heading: Nail salon
  cta-url: /contact
  cta-title: Book Now
- bg: main-slider-1-3.jpg
  tagline: ideal place to unwind
  heading: Hair Salon
  cta-url: /contact
  cta-title: Book Now
